services:
  postgres:
    container_name: postgres-demo
    image: postgres
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: demo_db
    volumes:
      - postgres:/data/postgres
    ports:
      - 5432:5432
    networks:
      - demo-spring
    restart: unless-stopped
  demo-api:
    container_name: demo-api
    image: dmo/dmo:1.0.0
    ports:
      - 8081:8081
    networks:
      - demo-spring
    depends_on:
      - postgres
  demo-frontend:
    container_name: demo-frontend
    image: dmo/dmo-ui:1.0.0
    ports:
      - 8080:80
    networks:
      - demo-spring
    depends_on:
      - demo-api

networks:
  demo-spring:
    driver: bridge

volumes:
  postgres:
    driver: local