services:
  postgres:
    container_name: postgres-demo
    image: postgres
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: demo_db
    volumes:
      - postgres:/data/postgres
    ports:
      - 5432:5432
    networks:
      - demo-spring
    restart: unless-stopped
networks:
  demo-spring:
    driver: bridge

volumes:
  postgres:
    driver: local