/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { StudentResponse } from '../../models/student-response';

export interface FindStudentById$Params {
  'student-id': number;
}

export function findStudentById(http: HttpClient, rootUrl: string, params: FindStudentById$Params, context?: HttpContext): Observable<StrictHttpResponse<StudentResponse>> {
  const rb = new RequestBuilder(rootUrl, findStudentById.PATH, 'get');
  if (params) {
    rb.path('student-id', params['student-id'], {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<StudentResponse>;
    })
  );
}

findStudentById.PATH = '/students/{student-id}';
