/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { DepartementResponse } from '../../models/departement-response';

export interface FindDepartementById$Params {
  'departement-id': number;
}

export function findDepartementById(http: HttpClient, rootUrl: string, params: FindDepartementById$Params, context?: HttpContext): Observable<StrictHttpResponse<DepartementResponse>> {
  const rb = new RequestBuilder(rootUrl, findDepartementById.PATH, 'get');
  if (params) {
    rb.path('departement-id', params['departement-id'], {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<DepartementResponse>;
    })
  );
}

findDepartementById.PATH = '/departements/{departement-id}';
