/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { DepartementResponse } from '../../models/departement-response';

export interface ListAllDepartement$Params {
}

export function listAllDepartement(http: HttpClient, rootUrl: string, params?: ListAllDepartement$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<DepartementResponse>>> {
  const rb = new RequestBuilder(rootUrl, listAllDepartement.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<DepartementResponse>>;
    })
  );
}

listAllDepartement.PATH = '/departements';
