/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export { DepartementRequest } from './models/departement-request';
export { DepartementResponse } from './models/departement-response';
export { StudentRequest } from './models/student-request';
export { StudentResponse } from './models/student-response';
export { UpdateDepartementRequest } from './models/update-departement-request';
export { UpdateStudentRequest } from './models/update-student-request';
