/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export { StudentsService } from './services/students.service';
export { DepartementsService } from './services/departements.service';
